version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.16.2
    steps:
      - checkout
      - run:
          name: Run Download
          command: |
              go mod download
      - run:
          name: Run vet
          command: |
              go vet ./...
      - run:
          name: Run staticheck
          command: |
              wget -O staticcheck.tgz https://github.com/dominikh/go-tools/releases/download/2020.2.1/staticcheck_linux_amd64.tar.gz
              tar -xzf staticcheck.tgz
              ./staticcheck/staticcheck --version
              ./staticcheck/staticcheck ./...
      - run:
          name: Run tests
          command: 
              go test -v ./...
